In [ ]:
import numpy as np
arr1=np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [2]:
print(arr1.shape)

(3,)


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
#Reshaping an Array
arr2=np.array([[1, 2, 3, 4, 5, 6]])
reshaped_arr=arr2.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#Creating an 2D array directly
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print("The shape of array is ", arr3.shape)

[[1 2 3]
 [4 5 6]]
The shape of array is  (2, 3)


In [11]:
arr4 = np.arange(0,10,2)
print(arr4)
arr_reshaped = arr4.reshape(5,1)
print(arr_reshaped)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [12]:
ones_Arr = np.ones((3,4))
print(ones_Arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
identity_Arr = np.eye(4)
print(identity_Arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#Array Attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type of elements:", arr.dtype)
print("Size of each element in bytes:", arr.itemsize)
print("Total number of elements:", arr.size)
print("Total size of the array in bytes:", arr.nbytes)


Shape of the array: (2, 3)
Number of dimensions: 2
Data type of elements: int64
Size of each element in bytes: 8
Total number of elements: 6
Total size of the array in bytes: 48


In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [16]:
#Universal Functions
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Sine:", np.sin(arr))
print("Logarithm:", np.log(arr))   


Square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [18]:
#Array Slicing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array:\n", arr)
print(arr[0,0])
print(arr[1:, 1:3])
print(arr[:, 2])
print(arr[1:,1:3])
#Modifying Array Elements
arr[0,0]=100
arr[1:,:]=100

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 6  7]
 [10 11]]
[ 3  7 11]
[[ 6  7]
 [10 11]]


In [20]:
#Statistical Operations
data  = np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean:", np.mean(data))
print("Median:", np.median(data))   
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))

print(data>5)
print(data[data>5])
print(data[(data>5) & (data<8)]) 

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7]
